# ===============
# PUBLISH RELEASE
# ===============

name: Publish

# Activation Events
# =================

on:
  # When a release is published or edited
  release:
    types: [published, edited]

# Jobs
# ====

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      # Actions/Checkout âœ…
      # -------------------

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
    
      # Install dependencies and Build ğŸ“¦
      # ---------------------------------

      - name: Install dependencies and build
        run: npm ci && npm run build
    
      # Build and Tag ğŸ·
      # ----------------

      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}